### ISSUE TITLE
Type hasn't be translated

### ISSUE THREAD

**Issue by MageeLin** [bpmn-io/properties-panel#136] opened 2022-02-25 07:36 UTC
when use the bpmn-js-properties-panel@alpha5 and config the translate module, I found the element type in panel header hasn't be translated.
![image](https://user-images.githubusercontent.com/32347241/155674740-b172a6d3-b6dd-4039-bd6c-808c665ccd08.png)

After read the source code, I think this line should use `translate()`
https://github.com/bpmn-io/properties-panel/blob/8da1c0c6823aa581b78c8da7b9a63a0b22621654/src/components/Header.js#L32

**Comment by smbea** [comment] 2022-02-25 08:22
Hello,
Thank you for your input. I will label the issue accordingly.

If you are deep into the code, feel free to submit your contribution for this with a pull request.

**Comment by pinussilvestrus** [comment] 2022-02-25 08:22
The properties panel core has no translation functionality at the moment since it's no diagram-js service.

There is an issue in the upper library though: https://github.com/bpmn-io/bpmn-js-properties-panel/issues/537

**Comment by smbea** [comment] 2022-02-25 08:25
Yes, I was considering this from the bpmn-js-properties-panel angle.
Since its a duplicate of https://github.com/bpmn-io/bpmn-js-properties-panel/issues/537, I will close this one

**Closed** 2022-02-25 08:26 UTC
Labels: bug, backlog, spring cleaning
