### ISSUE TITLE
Scrollbars of the popup are hidden

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/properties-panel#316] opened 2023-12-14 14:11 UTC
### Describe the Bug

Long content in the editor can't be properly worked on, as scrollbars are hidden.

There are 2 CSS rules, one in the editor, one in the properties panel, that actively hide the scrollbars.

<img width="323" alt="Bildschirmfoto 2023-12-14 um 15 04 00" src="https://github.com/bpmn-io/properties-panel/assets/56470362/362c95e9-a710-4310-bbbd-103f93451c3c">

<img width="753" alt="Bildschirmfoto 2023-12-14 um 15 04 19" src="https://github.com/bpmn-io/properties-panel/assets/56470362/096809a9-e627-4a99-929f-ce96c8386acf">

However, if we enable vertical scrollbars, there's an annoying right padding we should get rid of:

<img width="795" alt="Bildschirmfoto 2023-12-14 um 15 10 19" src="https://github.com/bpmn-io/properties-panel/assets/56470362/16aba970-eafa-4bcb-bc5e-1959e454c77c">

### Steps to Reproduce

1. Open popup editor
2. Add a lot of content
3. Scrolling is hard, no visible scrollbars

### Expected Behavior

The editor shows scrollbars when needed.

**Comment by nikku** [comment] 2023-12-14 19:31
@christian-konrad Is this a duplicate of a related downstream issue, maybe one of https://github.com/camunda/camunda-modeler/issues/3969, https://github.com/camunda/camunda-modeler/issues/3894?

**Comment by christian-konrad** [comment] 2023-12-15 09:23
@nikku yes, to https://github.com/camunda/camunda-modeler/issues/3894, @vsgoulart is working on it as we want to proceed here and it wasn't picked up yet

**Comment by nikku** [comment] 2023-12-15 09:41
Great stuff! Looking forward to get this fixed.

**Closed** 2024-01-09 08:11 UTC
Labels: bug, needs review
