### ISSUE TITLE
New FX FEEL toggle is misaligned and colors do not match in Web Modeler BPMN properties panel

### ISSUE THREAD

**Issue by christian-konrad** [bpmn-io/properties-panel#249] opened 2023-05-26 18:25 UTC
### Describe the Bug

New FX FEEL toggle (https://github.com/bpmn-io/properties-panel/pull/245) is misaligned and colors do not match in Web Modeler BPMN properties panel.

The fx is not in line with the label and is too close to it.

The active state is almost undiscerneable from the disabled one.

### Steps to Reproduce

See form editor properties panel from the above PR: 
![image](https://github.com/bpmn-io/properties-panel/assets/56470362/06ff5103-19fb-40bc-ba9d-64d68e7d3f40)

See Web Modeler:
![image](https://github.com/bpmn-io/properties-panel/assets/56470362/d18cb826-98b7-4ad6-a141-36bb1a2f9949)

<img width="363" alt="Bildschirmfoto 2023-05-26 um 20 23 33" src="https://github.com/bpmn-io/properties-panel/assets/56470362/6238073b-6d40-43b4-97a3-b24160f6a8e8">

### Expected Behavior

* FX to be in line with the label.
* More spacing between label and FX.
* Active state to be clearly visible.

Just as in this picture from the initial PR:

![image](https://github.com/bpmn-io/properties-panel/assets/56470362/a02afa4c-ebf7-42db-8b65-742657e1f1f3)

If it is actually a Web Modeler issue, please open a bug report there asap.

### Environment

- Host (Browser/Node version), if applicable: [e.g. MS Edge 18, Chrome 69, Node 10 LTS]
- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]

**Comment by pinussilvestrus** [comment] 2023-05-28 18:08
@marcellobarile @vpellegrino @bpmn-io/modeling-dev could it be that the web modeler is picking up the correct SVG but the wrong styles from `camunda-bpmn-js`?

I see that `bpmn-js-properties-panel` is not updated with `properties-panel@2.1.0` yet, [but the Web Modeler does so](https://github.com/camunda/web-modeler/blob/main/webapp/package.json#L54). So it's using the updated FX toggle, but with the old styles.

**Comment by barmac** [comment] 2023-05-29 11:09
Yeah, that could be the reason as Web Modeler uses `camunda-bpmn-js` stylesheets which are bundled at release time.

**Comment by pinussilvestrus** [comment] 2023-05-30 12:49
I think Christian mentioned that this one should have a higher priority as it's already in the Web Modeler. Can you already give a timeline for this? 

As far as I can see, it'd need a properties-panel version bump in bpmn-js-properties-panel, right?

**Comment by barmac** [comment] 2023-05-30 13:13
Let's bump it everywhere then. I believe we should also remove v1^ from bpmn-js-properties-panel deps.

**Comment by barmac** [comment] 2023-05-30 13:54
OK so if Web Modeler updates to `bpmn-js-properties-panel@1.26.0` and `camunda-bpmn-js@2.6.0`, the issue should be gone.

**Comment by vpellegrino** [comment] 2023-05-31 12:26
@barmac, about `camunda-bpmn-js` we already updated it in a separate PR.
I just created https://github.com/camunda/web-modeler/pull/4888 to upgrade also `bpmn-js-properties-panel`. Would you mind having a look when it's possible? Thank you!

**Comment by christian-konrad** [comment] 2023-06-04 10:25
@vpellegrino @barmac @pinussilvestrus 
it's still broken in Web Modeler, now with another style:

<img width="366" alt="image" src="https://github.com/bpmn-io/properties-panel/assets/56470362/0495c2ae-e686-4cd7-9582-2d0cc485647f">

Please make sure to fix it asap

**Comment by nikku** [comment] 2023-06-05 09:50
I can confirm that this is the current state, with all dependencies updated. 

We'd want to root cause where this discrepancy is coming from; why different styles are applied across form-js (individually styled there?) and other libraries that also build on top of `@bpmn-io/properties-panel`.

**Comment by pinussilvestrus** [comment] 2023-06-05 10:21
I think what happens here is that the Web Modeler includes two versions of the properties panel styles in the BPMN page. One from `camunda-bpmn-js` and one from form-js, which is bundling the properties panel styles together. In case we have a version mismatch, this can collide (cf. what we discussed over in https://github.com/camunda/web-modeler/pull/4888#issuecomment-1575622906).

I think we need to a bit more careful here. Either

* ensure we always include properties panel styles once, no matter what
  * one way to mitigate this is to not use the bundled version of the form-js styles, [which we didn't follow up on yet, unfortunately](https://github.com/camunda/web-modeler/issues/4238#issuecomment-1490411260)
  * also this one could cause problems, e.g. if we unintentionally use a properties panel stylesheet with not-yet updated form-js, or vice versa
* in case we need different versions, prefix the properties panel styles to a specific context (e.g. forms)
* something else?

**Comment by pinussilvestrus** [comment] 2023-06-05 14:24
> @pinussilvestrus I can [reproduce this with stock camunda-bpmn-js](https://github.com/bpmn-io/properties-panel/issues/249#issuecomment-1576481342), no form-js integration insight. Based on that I assume we're not bundling the right styles with @bpmn-io/properties-panel?

Ah, so you mean inside `camunda-bpmn-js` directly? When I check it out `main` locally and execute `npm run start:cloud`, it looks right to me ([given the styles that were required](https://github.com/bpmn-io/properties-panel/pull/245#issuecomment-1547837568
)).


![image](https://github.com/bpmn-io/properties-panel/assets/9433996/cf1dd643-6830-439f-842e-b528cf90753c)

**Comment by nikku** [comment] 2023-06-06 07:41
@pinussilvestrus Thanks for confirming; if this is the look we're going to ship, then it is fine.

Looking at @christian-konrad's comment (https://github.com/bpmn-io/properties-panel/issues/249#issuecomment-1575507104) and also checking it out myself I thought we maybe did not provide the proper spacing for icons.

![image](https://github.com/bpmn-io/properties-panel/assets/58601/d8e5132e-3a11-4f23-a457-01cfcc90e2de)

Here is an alternative version that is slightly more spacious. I find it easier for the eye:

![image](https://github.com/bpmn-io/properties-panel/assets/58601/efd1d7df-c325-4b85-b114-4d11c1bac52f)

**Comment by nikku** [comment] 2023-06-06 08:18
Moving this issue to _backlog_.

**Comment by RomanKostka** [comment] 2023-06-07 14:31
@pinussilvestrus 
Please find the updated styling [here](https://www.figma.com/file/CiTSN1vNETjIAy6W9jUIFp/Form-Editor?type=design&node-id=1087%3A150456&t=DM1BX9rnHpjrrAQZ-1):
![image](https://github.com/bpmn-io/properties-panel/assets/114994124/ed21fe65-5d9b-4934-a31b-ef253f277c9a)
![image](https://github.com/bpmn-io/properties-panel/assets/114994124/2da656bb-39b8-4ed5-935b-f32bc8e1caa6)


size and colors (states & background ) has been updated to fit into the existing layout.

**Comment by nikku** [comment] 2023-06-08 10:29
@RomanKostka [My proposal](https://github.com/bpmn-io/properties-panel/issues/249#issuecomment-1578100180) was to slightly reduce the visual presence of the `fx` toggle, to also make more space for "background boxes". Did you consider this?

**Comment by pinussilvestrus** [comment] 2023-06-13 09:49
Please find here the PR with the updated styles: https://github.com/bpmn-io/properties-panel/pull/251

@bpmn-io/modeling-dev is there any fast way to start up a demo of `camunda-bpmn-js` with a properties panel branch?

**Comment by barmac** [comment] 2023-06-13 11:32
For a single demo, I'd suggest to `npm link path-to-properties-panel` and copy over the CSS from `node_modules/@bpmn-io/properties-panel` to `node_modules/bpmn-js-properties-panel/dist/assets`.

**Comment by pinussilvestrus** [comment] 2023-06-13 11:57
I rather meant a ready-to-use demo for @RomanKostka and @christian-konrad as we have for form-js (e.g. https://demo-update-fx-styles--camunda-form-playground.netlify.app/). I guess a code sandbox would be the only way or is there something similar for bpmn-js?

**Comment by nikku** [comment] 2023-06-13 12:21
@pinussilvestrus Should be possible to build something like that. Just a matter of priority at this point.

**Closed** 2023-06-14 15:20 UTC
Labels: bug, needs review
